"""
CandleStick_Patterns_Recognition - is a powerful set of tools for stock data analysis and manipulation 
======================================================================================================

See http://candles.paterns.recognition.com/ (ya eto prosto pridumal) for full documentation. Otherwise, see the
docstrings of the various objects in the CandleStick_Patterns_Recognition  namespace:

Here names of tools....
1....
2....
3....
"""
